name: Python Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Check pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle --ignore E501 .
        ...
